In [1]:
import numpy as np
import pandas as pd

Numpy --> n-dimensional array computation

Pandas --> data format specifically designed for data analysis (Series dan DataFrame)

In [15]:
my_list = [10,20,30,1]
my_list2 = [40,50,60,2]
my_list3 = [70,80,90,3]

my_2d_list = [my_list, my_list2, my_list3]

this_array = np.array(my_2d_list)
this_array.shape

(3, 4)

In [13]:
this_array[:, 2]

array([30, 60, 90])

In [20]:
this_array

array([[10, 20, 30,  1],
       [40, 50, 60,  2],
       [70, 80, 90,  3]])

In [23]:
this_array[2][2]

90

In [32]:
other_array = np.array([1,2,3])
this_array - other_array

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [28]:
this_array.shape

(3, 4)

In [37]:
other_array.reshape(3,1)

array([[1],
       [2],
       [3]])

In [36]:
this_array - other_array.reshape(3,1)

array([[ 9, 19, 29,  0],
       [38, 48, 58,  0],
       [67, 77, 87,  0]])

In [ ]:
jumlah baris yg sama
atau jumlah kolom yg sama dgn yg sebelah kiri

In [41]:
new_array = np.concatenate(
    (this_array, [[4,5,6,7]]), axis=1
)

new_array

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 1

In [39]:
np.array([[4,5,6,7]]).shape

(1, 4)

In [ ]:
jika mau nambah baris (axis=0) --> jumlah kolom di kiri = di kanan
jika mau nambah kolom (axis=1) --> jumlah baris di kiri = di kanan

In [42]:
df_restaurants = pd.read_csv('Datasets/Top250.csv')
df_restaurants

Rank           Restaurant  \
0       1           McDonald's   
1       2            Starbucks   
2       3          Chick-fil-A   
3       4            Taco Bell   
4       5          Burger King   
..    ...                  ...   
245   246      Rainforest Cafe   
246   247                  PDQ   
247   248        Lupe Tortilla   
248   249  Cook-Out Restaurant   
249   250             Jollibee   

                                               Content  Sales YOY_Sales  \
0                                                  NaN  40412      4.9%   
1                                                  NaN  21380      8.6%   
2    While Popeyes got a lot of the chicken buzz in...  11320     13.0%   
3                                                  NaN  11293      9.0%   
4                                                  NaN  10204      2.7%   
..                                                 ...    ...       ...   
245                                                NaN    129    -10.4%   
246                                                NaN    127     -5.5%   
247                                                NaN    127     12.1%   
248                                                NaN    126     10.1%   
249                                                NaN    126     15.2%   

     Units YOY_Units Headquarters             Segment_Category  
0    13846     -0.5%          NaN       Quick Service & Burger  
1    15049      3.0%          NaN  Quick Service & Coffee Cafe  
2     2470      5.0%          NaN      Quick Service & Chicken  
3     6766      2.7%          NaN      Quick Service & Mexican  
4     7346      0.2%          NaN       Quick Service & Burger  
..     ...       ...          ...                          ...  
245     18     -5.3%          NaN                  Varied Menu  
246     56    -11.1%          NaN                      Chicken  
247     25      8.7%          NaN                      Mexican  
248    270      7.1%          NaN                       Burger  
249     40     11.1%          NaN                      Chicken  

[250 rows x 9 columns]

In [43]:
df_restaurants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   Rank              250 non-null    int64 
 1   Restaurant        250 non-null    object
 2   Content           33 non-null     object
 3   Sales             250 non-null    int64 
 4   YOY_Sales         250 non-null    object
 5   Units             250 non-null    int64 
 6   YOY_Units         250 non-null    object
 7   Headquarters      52 non-null     object
 8   Segment_Category  250 non-null    object
dtypes: int64(3), object(6)
memory usage: 17.7+ KB


In [55]:
# float(df_restaurants['YOY_Sales'][0].replace('%', '')) / 100

# define a regular function, then apply it to every row
def convert_to_decimal(x):
    return float(x.replace('%', '')) / 100

df_restaurants['YOY_Sales'] = df_restaurants['YOY_Sales'].apply(convert_to_decimal)
# define a lambda function, idem
# df_restaurants['YOY_Sales'] = df_restaurants['YOY_Sales'].apply(lambda x: float(x.replace('%', '')) / 100)

In [59]:
df_restaurants[
    (df_restaurants['Segment_Category'] == 'Quick Service & Mexican')
    & (df_restaurants['Rank'].between(1,50))
]

Rank Restaurant Content  Sales  YOY_Sales  Units YOY_Units Headquarters  \
3     4  Taco Bell     NaN  11293       0.09   6766      2.7%          NaN   

          Segment_Category  
3  Quick Service & Mexican

In [67]:
df_restaurants[
    df_restaurants['Segment_Category'] == 'Quick Service & Burger'
].sort_values(by='YOY_Sales', ascending=False).iloc[:20]

Rank                     Restaurant  \
37    38                       Culver's   
29    30                    Whataburger   
0      1                     McDonald's   
12    13                 Sonic Drive-In   
49    50                In-N-Out Burger   
6      7                        Wendy's   
4      5                    Burger King   
75    76                   White Castle   
23    24                Jack in the Box   
84    85  Checkers Drive-In Restaurants   
42    43                     Carl's Jr.   
34    35                       Hardee's   
50    51                 Steak 'n Shake   

                                              Content  Sales  YOY_Sales  \
37  One of the country's fastest-growing chains ov...   1795      0.139   
29                                                NaN   2556      0.058   
0                                                 NaN  40412      0.049   
12  The drive-in chain grew same-store sales for t...   4687      0.046   
49                                                NaN    957      0.046   
6                                                 NaN   9762      0.042   
4                                                 NaN  10204      0.027   
75                                                NaN    579      0.024   
23                                                NaN   3504      0.011   
84                                                NaN    535     -0.018   
42                                                NaN   1423     -0.025   
34                                                NaN   2020     -0.040   
50  As of August, the chain had temporarily closed...    950     -0.077   

    Units YOY_Units Headquarters        Segment_Category  
37    732      6.7%          NaN  Quick Service & Burger  
29    830      0.6%          NaN  Quick Service & Burger  
0   13846     -0.5%          NaN  Quick Service & Burger  
12   3526     -2.1%          NaN  Quick Service & Burger  
49    351      3.5%          NaN  Quick Service & Burger  
6    5852      0.7%          NaN  Quick Service & Burger  
4    7346      0.2%          NaN  Quick Service & Burger  
75    371     -0.5%          NaN  Quick Service & Burger  
23   2243      0.3%          NaN  Quick Service & Burger  
84    584     -0.2%          NaN  Quick Service & Burger  
42   1095     -2.3%          NaN  Quick Service & Burger  
34   1820     -1.4%          NaN  Quick Service & Burger  
50    576     -3.0%          NaN  Quick Service & Burger

In [73]:
df_restaurants.groupby('Headquarters')['Sales'].mean()

Headquarters
Addison, TX             297.500000
Atlanta, GA             335.000000
Austin, TX              349.000000
Birmingham, AL          290.000000
Boston, MA              289.000000
Chattanooga, TN         275.000000
Cheyenne, WY            373.000000
Coppell, TX             410.000000
Countryside, IL         338.000000
Dallas, TX              398.333333
Denver, CO              289.000000
Doral, FL               340.000000
Dunwoody, GA            343.000000
Emeryville, CA          357.000000
Houston, TX             312.333333
Irvine, CA              265.000000
Irving, TX              325.333333
Lexington, KY           275.000000
Louisville, KY          404.000000
Miami, FL               425.000000
Minneapolis, MN         306.000000
Minnetonka, MN          329.000000
Mission Viejo, CA       259.000000
Nashville, TN           426.000000
New York, NY            281.000000
Oklahoma City, OK       268.000000
Orange City, IA         269.000000
Orlando, FL             253.000000
Pasaden

## Latihan Python for Analyst

In [4]:
import numpy as np
import pandas as pd
# 1
arr1 = np.array([[0,1,2],[3,4,5],[6,7,8]])
i = [1,2,0]
arr1[:,i]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])

In [5]:
# 2
np.array([[0.84593875,-0.93172626],[-0.74]])

<ipython-input-5-b9c6a8ff54d2>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[0.84593875,-0.93172626],[-0.74]])


array([list([0.84593875, -0.93172626]), list([-0.74])], dtype=object)

In [6]:
# 3
df = pd.read_csv('melb_data.csv')
df[df['Rooms']==4]['Price'].mean()

1445281.7358630951

In [7]:
# 4
arr = np.array([[1,2,3,4],[6,7,8,9],[10,11,12,13],[14,15,16,17]])
arr[1:3,1:3]

array([[ 7,  8],
       [11, 12]])

In [8]:
# 5
arr2 = np.array([[ 0,1,2,3, 4, 5, 6, 7],
[ 8, 9, 10, 11, 12, 13, 14, 15],
[16, 17, 18, 19, 20, 21, 22, 23],
[24, 25, 26, 27, 28, 29, 30, 31],
[32, 33, 34, 35, 36, 37, 38, 39]])
arr2[::2,3:6]

array([[ 3,  4,  5],
       [19, 20, 21],
       [35, 36, 37]])

In [18]:
# 6
df1 = pd.DataFrame( 
    { 
        'A': ['A0', 'A1', 'A2', 'A3'], 
        'B': ['B0', 'B1', 'B2', 'B3'], 
        'C': ['C0', 'C1', 'C2', 'C3'], 
        'D': ['D0', 'D1', 'D2', 'D3'], 
    }, 
    index=[0, 1, 2, 3] ) 
df2 = pd.DataFrame( 
    { 
        'B': ['B2', 'B3', 'B6', 'B7'], 
        'D': ['D2', 'D3', 'D6', 'D7'], 
        'F': ['F2', 'F3', 'F6', 'F7'], 
    }, 
index=[2, 3, 6, 7])
pd.concat([df1,df2], join='inner',axis=1)

A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

In [10]:
# 7
np.random.seed(10)
arr = np.random.randint(20, size=(2, 4))
print("arr[1, 1:3] + arr[0:3,2] = {}".format(arr[1, 1:3]+arr[0:3,2]))

arr[1, 1:3] + arr[0:3,2] = [31 34]


In [21]:
# 8
# pd.DataFrame(df['Type'].value_counts())
df['Rooms'].nunique()

9